// <auto-generated />
using System;
using API_REST_Core.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_REST_Core.Migrations
{
    [DbContext(typeof(EntityFrameworkCoreDbContext))]
    [Migration("20200826135946_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API_REST_Core.Models.Device", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("_idGateway");

                    b.Property<DateTime>("datecreated");

                    b.Property<int>("number");

                    b.Property<bool>("status");

                    b.Property<string>("vendor");

                    b.HasKey("_id");

                    b.HasIndex("_idGateway");

                    b.ToTable("Devices");

                    b.HasData(
                        new { _id = 1, _idGateway = 1, datecreated = new DateTime(2020, 8, 26, 9, 59, 35, 721, DateTimeKind.Local), number = 1, status = true, vendor = "Huawei Co" }
                    );
                });

            modelBuilder.Entity("API_REST_Core.Models.Gateway", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ipv4address");

                    b.Property<string>("name");

                    b.Property<string>("serialnumber");

                    b.HasKey("_id");

                    b.ToTable("Gateways");

                    b.HasData(
                        new { _id = 1, ipv4address = "192.168.0.1", name = "Santiago de Cuba", serialnumber = "43037b77003e7491720075c92b834a9cbd2e706d7687e0e0cbdbee5d4b0e5421" }
                    );
                });

            modelBuilder.Entity("API_REST_Core.Models.Device", b =>
                {
                    b.HasOne("API_REST_Core.Models.Gateway", "gateway")
                        .WithMany("devices")
                        .HasForeignKey("_idGateway")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
